#Lean first version.
PRODUCT_VERSION_MAJOR = 9.0
PRODUCT_VERSION_MAINTENANCE = LoL
LEAN_POSTFIX := $(shell date +"%Y%m%d")
LEAN_BUILD_EXTRA := By-Team-Lean
ifndef LEAN_BUILD_TYPE
    LEAN_BUILD_TYPE := UNOFFICIAL
endif

# Set all versions
LEAN_VERSION := LeanOS-$(LEAN_BUILD)-$(PRODUCT_VERSION_MAINTENANCE)-$(LEAN_BUILD_TYPE)-$(LEAN_POSTFIX)
LEAN_MOD_VERSION := LeanOS-$(LEAN_BUILD)-$(PRODUCT_VERSION_MAINTENANCE)-$(LEAN_BUILD_TYPE)-$(LEAN_POSTFIX)
LEAN_XTRA_VERSION := $(PRODUCT_VERSION_MAINTENANCE)-$(LEAN_BUILD_TYPE)
LEAN_DISPLAY_VERSION := $(LEAN_XTRA_VERSION)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    lean.ota.version=$(PRODUCT_VERSION_MAJOR)-$(PRODUCT_VERSION_MAINTENANCE) \
    ro.lean.version=$(LEAN_XTRA_VERSION) \
    ro.modversion=$(LEAN_MOD_VERSION) \
    ro.lean.buildtype=$(LEAN_BUILD_TYPE) \
    ro.lean.display.version=$(LEAN_DISPLAY_VERSION) \
    com.lean.fingerprint=$(LEAN_XTRA_VERSION)

